### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by JoD** [jezberg/loandra#1]
Hey all

Running Loandra using the [script](https://github.com/jezberg/loandra/files/3671526/loandra_run.sh.txt) and [instance](https://github.com/jezberg/loandra/files/3671524/test71--n-20000.wcnf.zip) gives a segmentation fault.

Kind regards - Jo

**Comment by jezberg** [comment]
Hello!
Thanks for letting me know!
The commit 9a8567b I just pushed fixed this on my computer, the instance now gets solved to optimality in just under a few seconds. Please let me know if you have any further problems, I am happy to help. 

Jeremias
