### ISSUE TITLE
Optimum reported but no "o" line with objective value

### ISSUE THREAD

**Issue by JoD** [jezberg/loandra#2]
Basically, the solver outputs the right value as a `c  Best solution: <some number>`, but not as a `o <value>` line. This is technically incorrect (not according to MaxSAT competition spec), and messes up my parser ;)

Should be easy to fix though. See file: [real-2.zip](https://github.com/jezberg/loandra/files/3735976/real-2.zip)

**Comment by jezberg** [comment]
Thanks, sorry for the late reply, I was travelling.
I fixed the issue. (commit 9e2e90a3422d0ebbed7542d245ab749603b667b7) 
The reason for it was the fact that the optimal cost of that instance is equal to the sum of weights of the soft clauses in it (an upper bound that is initialised without a model). This is of course still a valid MaxSAT instance and a corner case that I had not thought of. Thanks for helping me out!
