### ISSUE TITLE
How to set the total time limit?

### ISSUE THREAD

**Issue by Archer222arc** [jezberg/loandra#4]
Hi, is there any command for setting maximum running time? Thank you.

**Comment by jezberg** [comment]
Hi 
At the moment there is no command for a timeout in the solver. 
The solver will print the currently best known solution before terminating when 
receiving the SIGTERM signal. 
Hence a timeout can be enforced from outside the solver using various different method, e.g. running
`timeout XX ./loandra [options] [instance]`
in the terminal will terminate the solver after XX seconds and print the currently best known solution.
