### ISSUE TITLE
running make returns error

### ISSUE THREAD

**Issue by stanfris** [jezberg/loandra#6]
Encodings.cc:(.text.startup+0x9): undefined reference to `__asan_init'
/usr/bin/ld: Encodings.cc:(.text.startup+0xe): undefined reference to `__asan_version_mismatch_check_v8'
/usr/bin/ld: Encodings.cc:(.text.startup+0x23): undefined reference to `__asan_register_globals'
collect2: error: ld returned 1 exit status

This is the error I get when running make, I only performed the steps in cloning, I also updated the maxpre2 folder

Thanks in advance!

**Comment by jezberg** [comment]
Hi, 
I was unable to reproduce this error. There was however a small bug in the makefile related to something else, so maybe this was fixed as well? 

Can you check and get back to me. If you are still having the error i would appreciate if you let me know what platform you are on.
